#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width          0
bspc config window_gap            1
bspc config split_ratio           0.50
bspc config focus_follows_pointer true
